# Generated by Django 4.2.6 on 2023-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='número_de_colegiado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='dpi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='número_telefónico',
            field=models.CharField(max_length=20),
        ),
    ]
