# Generated by Django 4.2.6 on 2023-11-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_alter_medicos_número_de_colegiado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('médico_tratante', models.CharField(max_length=30)),
                ('nombre_del_paciente', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.CharField(max_length=30)),
                ('género', models.CharField(max_length=30)),
                ('dirección', models.CharField(max_length=50)),
                ('antecedentes_médicos', models.CharField(max_length=50)),
                ('receta_médica', models.CharField(max_length=100)),
                ('síntomas', models.CharField(max_length=50)),
                ('alergias', models.CharField(max_length=30)),
                ('diagnóstico', models.CharField(max_length=100)),
            ],
        ),
    ]
