# Generated by Django 4.2.6 on 2023-11-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electrónico', models.CharField(max_length=40)),
                ('asunto', models.CharField(max_length=60)),
                ('mensaje', models.CharField(max_length=170)),
            ],
        ),
    ]
